# Generated by Django 4.0.2 on 2022-03-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Game name')),
                ('price', models.IntegerField(default=0, verbose_name='Game price USD')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games-pics', verbose_name='Game cover')),
                ('description', models.TextField(verbose_name='Game description')),
                ('age_limit', models.IntegerField(default=0, verbose_name='Age limit')),
                ('development_company', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Development company')),
                ('genre', models.ForeignKey(default='No genre', on_delete=django.db.models.deletion.CASCADE, to='genres.genre', verbose_name='Game genre')),
            ],
        ),
    ]
