# Generated by Django 4.0.2 on 2022-03-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Company name')),
                ('desciption', models.TextField(blank=True, null=True, verbose_name='Company description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies-pics', verbose_name='Company logo')),
            ],
        ),
    ]
