# Generated by Django 4.0.2 on 2022-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Genre name')),
                ('desciption', models.TextField(blank=True, null=True, verbose_name='Genre description')),
            ],
        ),
    ]
