# Generated by Django 4.0.2 on 2022-03-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(default='No genre', on_delete=django.db.models.deletion.CASCADE, to='genres.genre', verbose_name='Game genre'),
        ),
    ]
